- name: Copying Mongodb Repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: latest

- name: Update MongoDB listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'


#echo -e "\e[33mStarting mongodb service\e[0m"
#systemctl enable mongod &>>/tmp/roboshop.log
#systemctl restart mongod &>>/tmp/roboshop.log
- name: Start MongoDB Service
  ansible.builtin.systemd:
    state: restarted
    name: mongod
    enabled: true

